/*
 * The MIT License
 *
 * Copyright 2019 kaique.mota.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.autogeral.paygo.controlpay.model;

import br.com.autogeral.paygo.controlpay.web.WsHelper;
import java.util.List;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

/**
 *
 * @author kaique.mota
 */
public class TerminalGetIdTeste {

    private static final String NOME = "";
    private static final boolean SOLICITAR_REFERENCIA = true;
    private static final boolean SOLOCITAR_CLIENTE = false;
    private static final boolean SOLICITAR_OPERADOR = false;
    private static final String IDENTIFICADOR_TEF = "05471416000101";
    private static final String RASTREAR_INTERVALO = "";
    private static final boolean PERMITE_VENDA_PARCELADA = true;
    private static final String PARCELAMENTO_PADRAO = "Loja";
    private static final boolean PERMITE_DESCONTO = false;
    private static final boolean PERMITE_ACRESCIMO = false;
    private static final boolean AGUARDA_TEF = true;
    private static final boolean HABILITAR_PDV = true;
    private static final boolean VENDA_POR_VALOR = true;
    private static final boolean VENDA_POR_PRODUTO = false;
    private static final boolean HABILITAR_PEDIDOS = false;
    private static final boolean IMPRESSAO_AUTOMARICA = false;
    private static final boolean IMPRIMIR_PRODUTOS = false;
    private static final boolean IMPRIMIR_CUPOM_LOJISTA = false;
    private static final boolean IMPRIMIR_CUPOM_CLIENTE = false;
    private static final String IMPRESSORA = null;
    private static final int PESSOA_ID = 8149;
    private static final String NOME_RAZAO_SOCIAL = "AUTO GERAL AUTOPECAS LTDA";
    private static final String SOBRENOME_NOME_FANTASIA = "AUTO GERAL AUTOPECAS LTDA";
    private static final String CPF_CNPJ = "05437537000137";
    private static final String CPF_CNPJ_FORMAT = "05.437.537/0001-37";
    private static final String EMAIL = "kaique.motta@autogeral.com.br";
    private static final String PESSOA_STATUS_NOME = "Ativo Vendedor";
    private static final int PESSOA_STATUS_ID = 2;
    private static final int TERMINAL_FISICO_ID = 216;
    private static final String TERMINAL_FISICO_NOME = "Terminal 00";
    private static final int TERMINAL_PARAMETROS_ID = 12276;
    private static final boolean TERMINAL_PARAMETROS_VALOR = true;
    private static final int PARAMETRO_ID = 80;
    private static final String PARAMETRO_NOME = "permiteVendaParcelada";
    private static final String PARAMETRO_DESCRICAO = "Parâmetro para o vendedor configurar se permite ou não venda parcelada";
    private static final String PARAMETRO_VALOR = null;
    private static final int TERMINAL_ID = 900;
    private static final String TERMINAL_NOME = "TERMINAL 900";
    private static final boolean PESSOA_JURIDICA = true;
    private static final String INSTALACAO_ID = "450137";

    @Test
    public void testSerialize() {
        Terminal ter = new Terminal();
        ter.setId(TERMINAL_ID);
        ter.setNome(TERMINAL_NOME);
        ter.setSolicitarReferencia(SOLICITAR_REFERENCIA);
        ter.setSolicitarCliente(SOLOCITAR_CLIENTE);
        ter.setSolicitarOperador(SOLICITAR_OPERADOR);
        ter.setIdentificadorTef(IDENTIFICADOR_TEF);
        ter.setRastrearIntervalo(RASTREAR_INTERVALO);
        ter.setPermiteVendaParcelada(PERMITE_VENDA_PARCELADA);
        ter.setParcelamentoPadrao(PARCELAMENTO_PADRAO);
        ter.setPermiteDesconto(PERMITE_DESCONTO);
        ter.setPermiteAcrescimo(PERMITE_ACRESCIMO);
        ter.setAguardaTef(AGUARDA_TEF);
        ter.setHabilitarPDV(HABILITAR_PDV);
        ter.setVendaPorValor(VENDA_POR_VALOR);
        ter.setVendaPorProduto(VENDA_POR_PRODUTO);
        ter.setHabilitarPedidos(HABILITAR_PEDIDOS);
        ter.setImpressaoAutomatica(IMPRESSAO_AUTOMARICA);
        ter.setImpressaoAutomatica(IMPRESSAO_AUTOMARICA);
        ter.setImprimirProdutos(IMPRIMIR_PRODUTOS);
        ter.setImprimirCupomLojista(IMPRIMIR_CUPOM_LOJISTA);
        ter.setImprimirCupomCliente(IMPRIMIR_CUPOM_CLIENTE);
        LoginPessoa pessoa = new LoginPessoa();
        pessoa.setId(PESSOA_ID);
        pessoa.setNomeRazaoSocial(NOME_RAZAO_SOCIAL);
        pessoa.setSobrenomeNomeFantasia(SOBRENOME_NOME_FANTASIA);
        pessoa.setCpfCnpj(CPF_CNPJ);
        pessoa.setCpfCnpjFormat(CPF_CNPJ_FORMAT);
        pessoa.setEmail(EMAIL);
        PessoaStatus status = new PessoaStatus();
        status.setNome(PESSOA_STATUS_NOME);
        status.setId(PESSOA_STATUS_ID);
        TerminalFisico fisico = new TerminalFisico();
        fisico.setId(PESSOA_ID);
        fisico.setNome(NOME);
        fisico.setInstalacaoId(INSTALACAO_ID);
        TerminalParametro terminalParametro = new TerminalParametro();
        terminalParametro.setId(TERMINAL_PARAMETROS_ID);
        terminalParametro.setValor(TERMINAL_PARAMETROS_VALOR);
        Parametro parametro = new Parametro();
        parametro.setId(PARAMETRO_ID);
        parametro.setNome(PARAMETRO_NOME);
        parametro.setDescricao(PARAMETRO_DESCRICAO);
        parametro.setValor(PARAMETRO_VALOR);
        ter.setId(TERMINAL_ID);
        ter.setNome(TERMINAL_NOME);
        pessoa.setPessoaJuridica(PESSOA_JURIDICA);
        fisico.setInstalacaoId(INSTALACAO_ID);

    }

    /* https://docs.controlpay.com.br/?version=latest#50fcf7b2-0b4d-5627-ddba-100a1f15a5e0*/
    @Test
    public void testParseData() {

        String toParse = "{\n"
                + "    \"data\": \"26/09/2019 17:08:58.8010\",\n"
                + "    \"terminais\": [\n"
                + "        {\n"
                + "            \"id\": " + TERMINAL_ID + ",\n"
                + "            \"nome\": \"" + TERMINAL_NOME + "\",\n"
                + "            \"solicitarReferencia\": " + SOLICITAR_REFERENCIA + ",\n"
                + "            \"solicitarCliente\": " + SOLOCITAR_CLIENTE + ",\n"
                + "            \"solicitarOperador\": " + SOLICITAR_OPERADOR + ",\n"
                + "            \"identificadorTef\": \"" + IDENTIFICADOR_TEF + "\",\n"
                + "            \"rastrearIntervalo\": \"" + RASTREAR_INTERVALO + "\",\n"
                + "            \"permiteVendaParcelada\": " + PERMITE_VENDA_PARCELADA + ",\n"
                + "            \"parcelamentoPadrao\": \"" + PARCELAMENTO_PADRAO + "\",\n"
                + "            \"permiteDesconto\": " + PERMITE_DESCONTO + ",\n"
                + "            \"permiteAcrescimo\": " + PERMITE_ACRESCIMO + ",\n"
                + "            \"aguardaTef\": " + AGUARDA_TEF + ",\n"
                + "            \"habilitarPDV\": " + HABILITAR_PDV + ",\n"
                + "            \"vendaPorValor\": " + VENDA_POR_VALOR + ",\n"
                + "            \"vendaPorProduto\": " + VENDA_POR_PRODUTO + ",\n"
                + "            \"habilitarPedidos\": " + HABILITAR_PEDIDOS + ",\n"
                + "            \"impressaoAutomatica\": " + IMPRESSAO_AUTOMARICA + ",\n"
                + "            \"imprimirProdutos\": " + IMPRIMIR_PRODUTOS + ",\n"
                + "            \"imprimirCupomLojista\": " + IMPRIMIR_CUPOM_LOJISTA + ",\n"
                + "            \"imprimirCupomCliente\": " + IMPRIMIR_CUPOM_CLIENTE + ",\n"
                + "            \"impressora\": " + IMPRESSORA + ",\n"
                + "            \"pessoa\": {\n"
                + "                \"id\": " + PESSOA_ID + ",\n"
                + "                \"nomeRazaoSocial\": \"" + NOME_RAZAO_SOCIAL + "\",\n"
                + "                \"sobrenomeNomeFantasia\": \"" + SOBRENOME_NOME_FANTASIA + "\",\n"
                + "                \"pessoaJuridica\": " + PESSOA_JURIDICA + ",\n"
                + "                \"cpfCnpj\": \"" + CPF_CNPJ + "\",\n"
                + "                \"cpfCnpjFormat\": \"" + CPF_CNPJ_FORMAT + "\",\n"
                + "                \"email\": \"" + EMAIL + "\",\n"
                + "                \"pessoaStatus\": {\n"
                + "                    \"id\": " + PESSOA_STATUS_ID + ",\n"
                + "                    \"nome\": \"" + PESSOA_STATUS_NOME + "\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalFisico\": {\n"
                + "                \"id\": " + TERMINAL_FISICO_ID + ",\n"
                + "                \"nome\": \"" + TERMINAL_FISICO_NOME + "\",\n"
                + "                \"instalacaoId\": \"" + INSTALACAO_ID + "\",\n"
                + "                \"pessoa\": {\n"
                + "                    \"id\": " + PESSOA_ID + ",\n"
                + "                    \"nomeRazaoSocial\": \"" + NOME_RAZAO_SOCIAL + "\",\n"
                + "                    \"sobrenomeNomeFantasia\": \"" + SOBRENOME_NOME_FANTASIA + "\",\n"
                + "                    \"cpfCnpj\": \"" + CPF_CNPJ + "\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalParametros\": [\n"
                + "                {\n"
                + "                    \"id\": " + TERMINAL_PARAMETROS_ID + ",\n"
                + "                    \"valor\": \"" + TERMINAL_PARAMETROS_VALOR + "\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": " + PARAMETRO_ID + ",\n"
                + "                        \"nome\": \"" + PARAMETRO_NOME + "\",\n"
                + "                        \"descricao\": \"" + PARAMETRO_DESCRICAO + "\",\n"
                + "                        \"valor\": " + PARAMETRO_VALOR + "\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12277,\n"
                + "                    \"valor\": \"loja\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 41,\n"
                + "                        \"nome\": \"parcelamentopadrao\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar forma de Parcelamento padão\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12278,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 42,\n"
                + "                        \"nome\": \"permiteDesconto\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com desconto\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12279,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 43,\n"
                + "                        \"nome\": \"permiteAcrescimo\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com acréscimo\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12280,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 44,\n"
                + "                        \"nome\": \"AguardaTef\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se o PDV vai aguardar o TEF iniciar a transação\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12281,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 64,\n"
                + "                        \"nome\": \"VendaPorValor\",\n"
                + "                        \"descricao\": \"Habilita Venda por valor na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12282,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 78,\n"
                + "                        \"nome\": \"VendaPorProduto\",\n"
                + "                        \"descricao\": \"Habilita Venda por produto na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12283,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 79,\n"
                + "                        \"nome\": \"HabilitarPedidos\",\n"
                + "                        \"descricao\": \"Habilita pedidos na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12284,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 63,\n"
                + "                        \"nome\": \"HabilitarPDV\",\n"
                + "                        \"descricao\": \"Habilita PDV na tela vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12285,\n"
                + "                    \"valor\": \"\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 67,\n"
                + "                        \"nome\": \"RastrearIntervalo\",\n"
                + "                        \"descricao\": \"Tempo de Rastreamento do terminal\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12286,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 68,\n"
                + "                        \"nome\": \"SolicitarReferencia\",\n"
                + "                        \"descricao\": \"Solicitar referencia na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12287,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 81,\n"
                + "                        \"nome\": \"SolicitarOperador\",\n"
                + "                        \"descricao\": \"Solicitar operador na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12288,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 75,\n"
                + "                        \"nome\": \"imprimirProdutos\",\n"
                + "                        \"descricao\": \"Imprimir lista de produtos de uma Intenção de venda ou Pedido\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12289,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 76,\n"
                + "                        \"nome\": \"imprimirCupomLojista\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Lojista\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12290,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 77,\n"
                + "                        \"nome\": \"imprimirCupomCliente\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Cliente\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12291,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 69,\n"
                + "                        \"nome\": \"ImpressaoAutomatica\",\n"
                + "                        \"descricao\": \"ImpressaoAutomatica\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12292,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 70,\n"
                + "                        \"nome\": \"SolicitarCliente\",\n"
                + "                        \"descricao\": \"Solicita cliente na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12293,\n"
                + "                    \"valor\": \"05471416000101\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 66,\n"
                + "                        \"nome\": \"IdentificadorTef\",\n"
                + "                        \"descricao\": \"Identificador Tef\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 868,\n"
                + "            \"nome\": \"Terminal 01\",\n"
                + "            \"solicitarReferencia\": false,\n"
                + "            \"solicitarCliente\": false,\n"
                + "            \"solicitarOperador\": false,\n"
                + "            \"identificadorTef\": \"05471416000101\",\n"
                + "            \"rastrearIntervalo\": \"\",\n"
                + "            \"permiteVendaParcelada\": true,\n"
                + "            \"parcelamentoPadrao\": \"loja\",\n"
                + "            \"permiteDesconto\": false,\n"
                + "            \"permiteAcrescimo\": false,\n"
                + "            \"aguardaTef\": true,\n"
                + "            \"habilitarPDV\": true,\n"
                + "            \"vendaPorValor\": true,\n"
                + "            \"vendaPorProduto\": false,\n"
                + "            \"habilitarPedidos\": false,\n"
                + "            \"impressaoAutomatica\": false,\n"
                + "            \"imprimirProdutos\": false,\n"
                + "            \"imprimirCupomLojista\": false,\n"
                + "            \"imprimirCupomCliente\": false,\n"
                + "            \"impressora\": null,\n"
                + "            \"pessoa\": {\n"
                + "                \"id\": 8149,\n"
                + "                \"nomeRazaoSocial\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                \"sobrenomeNomeFantasia\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                \"pessoaJuridica\": true,\n"
                + "                \"cpfCnpj\": \"05437537000137\",\n"
                + "                \"cpfCnpjFormat\": \"05.437.537/0001-37\",\n"
                + "                \"email\": \"kaique.motta@autogeral.com.br\",\n"
                + "                \"pessoaStatus\": {\n"
                + "                    \"id\": 2,\n"
                + "                    \"nome\": \"Ativo Vendedor\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalFisico\": {\n"
                + "                \"id\": 226,\n"
                + "                \"nome\": \"Terminal 01\",\n"
                + "                \"instalacaoId\": \"298896\",\n"
                + "                \"pessoa\": {\n"
                + "                    \"id\": 8149,\n"
                + "                    \"nomeRazaoSocial\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                    \"sobrenomeNomeFantasia\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                    \"cpfCnpj\": \"05437537000137\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalParametros\": [\n"
                + "                {\n"
                + "                    \"id\": 12520,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 80,\n"
                + "                        \"nome\": \"permiteVendaParcelada\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda parcelada\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12521,\n"
                + "                    \"valor\": \"loja\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 41,\n"
                + "                        \"nome\": \"parcelamentopadrao\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar forma de Parcelamento padão\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12522,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 42,\n"
                + "                        \"nome\": \"permiteDesconto\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com desconto\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12523,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 43,\n"
                + "                        \"nome\": \"permiteAcrescimo\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com acréscimo\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12524,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 44,\n"
                + "                        \"nome\": \"AguardaTef\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se o PDV vai aguardar o TEF iniciar a transação\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12525,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 64,\n"
                + "                        \"nome\": \"VendaPorValor\",\n"
                + "                        \"descricao\": \"Habilita Venda por valor na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12526,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 78,\n"
                + "                        \"nome\": \"VendaPorProduto\",\n"
                + "                        \"descricao\": \"Habilita Venda por produto na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12527,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 79,\n"
                + "                        \"nome\": \"HabilitarPedidos\",\n"
                + "                        \"descricao\": \"Habilita pedidos na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12528,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 63,\n"
                + "                        \"nome\": \"HabilitarPDV\",\n"
                + "                        \"descricao\": \"Habilita PDV na tela vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12529,\n"
                + "                    \"valor\": \"05471416000101\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 66,\n"
                + "                        \"nome\": \"IdentificadorTef\",\n"
                + "                        \"descricao\": \"Identificador Tef\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12530,\n"
                + "                    \"valor\": \"\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 67,\n"
                + "                        \"nome\": \"RastrearIntervalo\",\n"
                + "                        \"descricao\": \"Tempo de Rastreamento do terminal\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12531,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 68,\n"
                + "                        \"nome\": \"SolicitarReferencia\",\n"
                + "                        \"descricao\": \"Solicitar referencia na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12532,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 81,\n"
                + "                        \"nome\": \"SolicitarOperador\",\n"
                + "                        \"descricao\": \"Solicitar operador na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12533,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 75,\n"
                + "                        \"nome\": \"imprimirProdutos\",\n"
                + "                        \"descricao\": \"Imprimir lista de produtos de uma Intenção de venda ou Pedido\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12534,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 76,\n"
                + "                        \"nome\": \"imprimirCupomLojista\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Lojista\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12535,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 77,\n"
                + "                        \"nome\": \"imprimirCupomCliente\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Cliente\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12536,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 69,\n"
                + "                        \"nome\": \"ImpressaoAutomatica\",\n"
                + "                        \"descricao\": \"ImpressaoAutomatica\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 12537,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 70,\n"
                + "                        \"nome\": \"SolicitarCliente\",\n"
                + "                        \"descricao\": \"Solicita cliente na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 898,\n"
                + "            \"nome\": \"Terminal 02\",\n"
                + "            \"solicitarReferencia\": false,\n"
                + "            \"solicitarCliente\": false,\n"
                + "            \"solicitarOperador\": false,\n"
                + "            \"identificadorTef\": \"05471416000101\",\n"
                + "            \"rastrearIntervalo\": \"\",\n"
                + "            \"permiteVendaParcelada\": true,\n"
                + "            \"parcelamentoPadrao\": \"loja\",\n"
                + "            \"permiteDesconto\": false,\n"
                + "            \"permiteAcrescimo\": false,\n"
                + "            \"aguardaTef\": true,\n"
                + "            \"habilitarPDV\": true,\n"
                + "            \"vendaPorValor\": true,\n"
                + "            \"vendaPorProduto\": false,\n"
                + "            \"habilitarPedidos\": false,\n"
                + "            \"impressaoAutomatica\": true,\n"
                + "            \"imprimirProdutos\": true,\n"
                + "            \"imprimirCupomLojista\": true,\n"
                + "            \"imprimirCupomCliente\": true,\n"
                + "            \"impressora\": {\n"
                + "                \"id\": 303,\n"
                + "                \"nome\": \"MP-4200 TH\"\n"
                + "            },\n"
                + "            \"pessoa\": {\n"
                + "                \"id\": 8149,\n"
                + "                \"nomeRazaoSocial\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                \"sobrenomeNomeFantasia\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                \"pessoaJuridica\": true,\n"
                + "                \"cpfCnpj\": \"05437537000137\",\n"
                + "                \"cpfCnpjFormat\": \"05.437.537/0001-37\",\n"
                + "                \"email\": \"kaique.motta@autogeral.com.br\",\n"
                + "                \"pessoaStatus\": {\n"
                + "                    \"id\": 2,\n"
                + "                    \"nome\": \"Ativo Vendedor\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalFisico\": {\n"
                + "                \"id\": 249,\n"
                + "                \"nome\": \"terminal 02\",\n"
                + "                \"instalacaoId\": \"532527\",\n"
                + "                \"pessoa\": {\n"
                + "                    \"id\": 8149,\n"
                + "                    \"nomeRazaoSocial\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                    \"sobrenomeNomeFantasia\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                    \"cpfCnpj\": \"05437537000137\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalParametros\": [\n"
                + "                {\n"
                + "                    \"id\": 13061,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 80,\n"
                + "                        \"nome\": \"permiteVendaParcelada\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda parcelada\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13062,\n"
                + "                    \"valor\": \"loja\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 41,\n"
                + "                        \"nome\": \"parcelamentopadrao\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar forma de Parcelamento padão\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13063,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 42,\n"
                + "                        \"nome\": \"permiteDesconto\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com desconto\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13064,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 43,\n"
                + "                        \"nome\": \"permiteAcrescimo\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com acréscimo\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13065,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 44,\n"
                + "                        \"nome\": \"AguardaTef\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se o PDV vai aguardar o TEF iniciar a transação\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13066,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 64,\n"
                + "                        \"nome\": \"VendaPorValor\",\n"
                + "                        \"descricao\": \"Habilita Venda por valor na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13067,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 78,\n"
                + "                        \"nome\": \"VendaPorProduto\",\n"
                + "                        \"descricao\": \"Habilita Venda por produto na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13068,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 79,\n"
                + "                        \"nome\": \"HabilitarPedidos\",\n"
                + "                        \"descricao\": \"Habilita pedidos na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13069,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 63,\n"
                + "                        \"nome\": \"HabilitarPDV\",\n"
                + "                        \"descricao\": \"Habilita PDV na tela vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13070,\n"
                + "                    \"valor\": \"05471416000101\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 66,\n"
                + "                        \"nome\": \"IdentificadorTef\",\n"
                + "                        \"descricao\": \"Identificador Tef\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13071,\n"
                + "                    \"valor\": \"\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 67,\n"
                + "                        \"nome\": \"RastrearIntervalo\",\n"
                + "                        \"descricao\": \"Tempo de Rastreamento do terminal\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13072,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 68,\n"
                + "                        \"nome\": \"SolicitarReferencia\",\n"
                + "                        \"descricao\": \"Solicitar referencia na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13073,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 81,\n"
                + "                        \"nome\": \"SolicitarOperador\",\n"
                + "                        \"descricao\": \"Solicitar operador na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13074,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 75,\n"
                + "                        \"nome\": \"imprimirProdutos\",\n"
                + "                        \"descricao\": \"Imprimir lista de produtos de uma Intenção de venda ou Pedido\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13075,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 76,\n"
                + "                        \"nome\": \"imprimirCupomLojista\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Lojista\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13076,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 77,\n"
                + "                        \"nome\": \"imprimirCupomCliente\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Cliente\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13077,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 69,\n"
                + "                        \"nome\": \"ImpressaoAutomatica\",\n"
                + "                        \"descricao\": \"ImpressaoAutomatica\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13078,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 70,\n"
                + "                        \"nome\": \"SolicitarCliente\",\n"
                + "                        \"descricao\": \"Solicita cliente na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 900,\n"
                + "            \"nome\": \"Terminal 03\",\n"
                + "            \"solicitarReferencia\": false,\n"
                + "            \"solicitarCliente\": false,\n"
                + "            \"solicitarOperador\": false,\n"
                + "            \"identificadorTef\": \"05471416000101\",\n"
                + "            \"rastrearIntervalo\": \"\",\n"
                + "            \"permiteVendaParcelada\": true,\n"
                + "            \"parcelamentoPadrao\": \"loja\",\n"
                + "            \"permiteDesconto\": false,\n"
                + "            \"permiteAcrescimo\": false,\n"
                + "            \"aguardaTef\": true,\n"
                + "            \"habilitarPDV\": true,\n"
                + "            \"vendaPorValor\": true,\n"
                + "            \"vendaPorProduto\": false,\n"
                + "            \"habilitarPedidos\": true,\n"
                + "            \"impressaoAutomatica\": false,\n"
                + "            \"imprimirProdutos\": false,\n"
                + "            \"imprimirCupomLojista\": false,\n"
                + "            \"imprimirCupomCliente\": false,\n"
                + "            \"impressora\": {\n"
                + "                \"id\": 303,\n"
                + "                \"nome\": \"MP-4200 TH\"\n"
                + "            },\n"
                + "            \"pessoa\": {\n"
                + "                \"id\": 8149,\n"
                + "                \"nomeRazaoSocial\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                \"sobrenomeNomeFantasia\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                \"pessoaJuridica\": true,\n"
                + "                \"cpfCnpj\": \"05437537000137\",\n"
                + "                \"cpfCnpjFormat\": \"05.437.537/0001-37\",\n"
                + "                \"email\": \"kaique.motta@autogeral.com.br\",\n"
                + "                \"pessoaStatus\": {\n"
                + "                    \"id\": 2,\n"
                + "                    \"nome\": \"Ativo Vendedor\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalFisico\": {\n"
                + "                \"id\": 251,\n"
                + "                \"nome\": \"Terminal 03\",\n"
                + "                \"instalacaoId\": \"493899\",\n"
                + "                \"pessoa\": {\n"
                + "                    \"id\": 8149,\n"
                + "                    \"nomeRazaoSocial\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                    \"sobrenomeNomeFantasia\": \"AUTO GERAL AUTOPECAS LTDA\",\n"
                + "                    \"cpfCnpj\": \"05437537000137\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"terminalParametros\": [\n"
                + "                {\n"
                + "                    \"id\": 13097,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 80,\n"
                + "                        \"nome\": \"permiteVendaParcelada\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda parcelada\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13098,\n"
                + "                    \"valor\": \"loja\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 41,\n"
                + "                        \"nome\": \"parcelamentopadrao\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar forma de Parcelamento padão\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13099,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 42,\n"
                + "                        \"nome\": \"permiteDesconto\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com desconto\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13100,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 43,\n"
                + "                        \"nome\": \"permiteAcrescimo\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se permite ou não venda com acréscimo\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13101,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 44,\n"
                + "                        \"nome\": \"AguardaTef\",\n"
                + "                        \"descricao\": \"Parâmetro para o vendedor configurar se o PDV vai aguardar o TEF iniciar a transação\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13102,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 64,\n"
                + "                        \"nome\": \"VendaPorValor\",\n"
                + "                        \"descricao\": \"Habilita Venda por valor na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13103,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 78,\n"
                + "                        \"nome\": \"VendaPorProduto\",\n"
                + "                        \"descricao\": \"Habilita Venda por produto na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13104,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 79,\n"
                + "                        \"nome\": \"HabilitarPedidos\",\n"
                + "                        \"descricao\": \"Habilita pedidos na tela Vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13105,\n"
                + "                    \"valor\": \"true\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 63,\n"
                + "                        \"nome\": \"HabilitarPDV\",\n"
                + "                        \"descricao\": \"Habilita PDV na tela vender\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13106,\n"
                + "                    \"valor\": \"05471416000101\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 66,\n"
                + "                        \"nome\": \"IdentificadorTef\",\n"
                + "                        \"descricao\": \"Identificador Tef\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13107,\n"
                + "                    \"valor\": \"\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 67,\n"
                + "                        \"nome\": \"RastrearIntervalo\",\n"
                + "                        \"descricao\": \"Tempo de Rastreamento do terminal\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13108,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 68,\n"
                + "                        \"nome\": \"SolicitarReferencia\",\n"
                + "                        \"descricao\": \"Solicitar referencia na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13109,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 81,\n"
                + "                        \"nome\": \"SolicitarOperador\",\n"
                + "                        \"descricao\": \"Solicitar operador na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13110,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 75,\n"
                + "                        \"nome\": \"imprimirProdutos\",\n"
                + "                        \"descricao\": \"Imprimir lista de produtos de uma Intenção de venda ou Pedido\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13111,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 76,\n"
                + "                        \"nome\": \"imprimirCupomLojista\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Lojista\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13112,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 77,\n"
                + "                        \"nome\": \"imprimirCupomCliente\",\n"
                + "                        \"descricao\": \"Imprimir cupom via do Cliente\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13113,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 69,\n"
                + "                        \"nome\": \"ImpressaoAutomatica\",\n"
                + "                        \"descricao\": \"ImpressaoAutomatica\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                },\n"
                + "                {\n"
                + "                    \"id\": 13114,\n"
                + "                    \"valor\": \"false\",\n"
                + "                    \"parametro\": {\n"
                + "                        \"id\": 70,\n"
                + "                        \"nome\": \"SolicitarCliente\",\n"
                + "                        \"descricao\": \"Solicita cliente na venda\",\n"
                + "                        \"valor\": null\n"
                + "                    }\n"
                + "                }\n"
                + "            ]\n"
                + "        }\n"
                + "    ]\n"
                + "}";

        Data d = WsHelper.unmarshal(toParse, Data.class);
        assertNotNull(d);
        List<Terminal> terminais = d.getTerminais();
        testeTerminal(terminais);
    }

    private void testeTerminal(List<Terminal> terminal) {
        assertNotNull(terminal);
        assertEquals(TERMINAL_ID, terminal.get(0).getId());
        assertEquals(TERMINAL_NOME, terminal.get(0).getNome());
        assertEquals(SOLICITAR_REFERENCIA, terminal.get(0).isSolicitarReferencia());
        assertEquals(SOLOCITAR_CLIENTE, terminal.get(0).isSolicitarCliente());
        assertEquals(SOLICITAR_OPERADOR, terminal.get(0).isSolicitarOperador());
        assertEquals(IDENTIFICADOR_TEF, terminal.get(0).getIdentificadorTef());
        assertEquals(RASTREAR_INTERVALO, terminal.get(0).getRastrearIntervalo());
        assertEquals(PERMITE_VENDA_PARCELADA, terminal.get(0).isPermiteVendaParcelada());
        assertEquals(PARCELAMENTO_PADRAO, terminal.get(0).getParcelamentoPadrao());
        assertEquals(PERMITE_DESCONTO, terminal.get(0).isPermiteDesconto());
        assertEquals(AGUARDA_TEF, terminal.get(0).isAguardaTef());
        assertEquals(HABILITAR_PDV, terminal.get(0).isHabilitarPDV());
        assertEquals(VENDA_POR_VALOR, terminal.get(0).isVendaPorValor());
        assertEquals(VENDA_POR_PRODUTO, terminal.get(0).isVendaPorProduto());
        assertEquals(HABILITAR_PEDIDOS, terminal.get(0).isHabilitarPedidos());
        assertEquals(IMPRESSAO_AUTOMARICA, terminal.get(0).isImpressaoAutomatica());
        assertEquals(IMPRIMIR_PRODUTOS, terminal.get(0).isImprimirProdutos());
        assertEquals(IMPRIMIR_CUPOM_LOJISTA, terminal.get(0).isImprimirCupomLojista());
        assertEquals(IMPRIMIR_CUPOM_CLIENTE, terminal.get(0).isImprimirCupomCliente());
        assertEquals(IMPRESSORA, terminal.get(0).getImpressora());
        LoginPessoa pessoa = terminal.get(0).getPessoa();
        assertEquals(PESSOA_ID, pessoa.getId());
        assertEquals(NOME_RAZAO_SOCIAL, pessoa.getNomeRazaoSocial());
        assertEquals(SOBRENOME_NOME_FANTASIA, pessoa.getSobrenomeNomeFantasia());
        assertEquals(PESSOA_JURIDICA, pessoa.isPessoaJuridica());
        assertEquals(CPF_CNPJ, pessoa.getCpfCnpj());
        assertEquals(CPF_CNPJ_FORMAT, pessoa.getCpfCnpjFormat());
        assertEquals(EMAIL, pessoa.getEmail());
        PessoaStatus pessoaStatus = terminal.get(0).getPessoa().getPessoaStatus();
        assertEquals(PESSOA_STATUS_ID, pessoaStatus.getId());
        assertEquals(PESSOA_STATUS_NOME, pessoaStatus.getNome());
        TerminalFisico terminalFisico = terminal.get(0).getTerminalFisico();
        assertEquals(TERMINAL_FISICO_ID, terminalFisico.getId());
        assertEquals(TERMINAL_FISICO_NOME, terminalFisico.getNome());
        assertEquals(INSTALACAO_ID, terminalFisico.getInstalacaoId());
        assertEquals(PESSOA_ID, pessoa.getId());
        assertEquals(NOME_RAZAO_SOCIAL, pessoa.getNomeRazaoSocial());
        assertEquals(SOBRENOME_NOME_FANTASIA, pessoa.getSobrenomeNomeFantasia());
        assertEquals(CPF_CNPJ, pessoa.getCpfCnpj());
        TerminalParametro terminalParametro = terminal.get(0).getTerminalParametros().get(0);
        assertEquals(TERMINAL_PARAMETROS_ID, terminalParametro.getId());
        assertEquals(TERMINAL_PARAMETROS_VALOR, terminalParametro.isValor());
        Parametro parametro = terminal.get(0).getTerminalParametros().get(0).getParametro();
        assertEquals(PARAMETRO_ID, parametro.getId());
        assertEquals(PARAMETRO_NOME, parametro.getNome());
        assertEquals(PARAMETRO_DESCRICAO, parametro.getDescricao());
        assertEquals(PARAMETRO_VALOR, parametro.getValor());

    }

}
