package br.com.autogeral.paygo.controlpay.model;

import br.com.autogeral.paygo.controlpay.web.WsHelper;
import java.util.List;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import org.junit.Test;

/**
 *
 * @author kaique.mota
 */
public class TokenClienteIdInsertTeste {

    private static final int CLIENTE_ID = 1;
    private static final int ID = 12;
    private static final boolean PREFERENCIAL = true;
    private static final int ID_CLIENTE = 1123;
    private static final String CPF_CNPJ = "05.471.416/0001-01";
    private static final String NOME_RAZAO_SOCIAL = "Cadastro Cliente";
    private static final String EMAIL = "cliente@mailinator.com";
    private static final String TELEFONE = null;
    private static final String DATA_INSERCAO = "07/07/2017 01:14";
    private static final String DATA_ATUALIZACAO = "01/10/2019";
    private static final String CARTAO_PAN = "444433******1111";
    private static final String CARTAO_VALIDADE = "00/00";
    private static final String BANDEIRA = "";
    private static final String CARTAO_TOKEN = "872bd127-0daf-4875-b872-a4a57846180a1931";
    private static final String GATE2ALLTOKEN = "213739b3-8f77-4c14-a8d7-323517997308";
    private static final int STATUS = 2;
    private static final String STATUS_DESCRICAO = "Ativo";
    private static final String URL_CAPTURAR_DADOS_CARTAO = "https://apidemo.gate2all.com.br/v1/save-card/213739b3-8f77-4c14-a8d7-323517997308";
    private static final int DRAW = 4;
    private static final int RECORDS_TOTAL = 11;
    private static final int RECORDS_FILTERED = 4;

    @Test
    public void testSerialize() {
        ClienteCartao cc = new ClienteCartao();
        cc.setId(ID);
        cc.setPreferencial(PREFERENCIAL);
        Cliente c = new Cliente();
        c.setId(ID_CLIENTE);
        c.setCpfCnpj(CPF_CNPJ);
        c.setNomeRazaoSocial(NOME_RAZAO_SOCIAL);
        c.setEmail(EMAIL);
        c.setTelefone(TELEFONE);
        cc.setDataInsercao(DATA_INSERCAO);
        cc.setCartaoPan(CARTAO_PAN);
        cc.setCartaoValidade(CARTAO_VALIDADE);
        cc.setBandeira(BANDEIRA);
        cc.setCartaoToken(CARTAO_TOKEN);
        cc.setGate2allToken(GATE2ALLTOKEN);
        cc.setStatus(STATUS);
        cc.setStatusDescricao(STATUS_DESCRICAO);
        cc.setUrlCapturarDadosCartao(URL_CAPTURAR_DADOS_CARTAO);

    }

    @Test
    public void testParse() {
        String toParse = "{\n"
                + "    \"draw\": " + DRAW + ",\n"
                + "    \"recordsTotal\": " + RECORDS_TOTAL + ",\n"
                + "    \"recordsFiltered\": " + RECORDS_FILTERED + ",\n"
                + "    \"data\": [\n"
                + "        {\n"
                + "            \"id\": " + ID + ",\n"
                + "            \"cliente\": {\n"
                + "                \"id\": " + CLIENTE_ID + ",\n"
                + "                \"cpfCnpj\": \"" + CPF_CNPJ + "\",\n"
                + "                \"nomeRazaoSocial\": \"" + NOME_RAZAO_SOCIAL + "\",\n"
                + "                \"email\": \"" + EMAIL + "\",\n"
                + "                \"telefone\": " + TELEFONE + "\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"" + DATA_ATUALIZACAO + "\",\n"
                + "            \"dataInsercao\": \"" + DATA_INSERCAO + "\",\n"
                + "            \"cartaoPan\": \"" + CARTAO_PAN + "\",\n"
                + "            \"cartaoValidade\": \"" + CARTAO_VALIDADE + "\",\n"
                + "            \"bandeira\": \"\",\n"
                + "            \"cartaoToken\": \"" + CARTAO_TOKEN + "\",\n"
                + "            \"gate2allToken\": \"" + GATE2ALLTOKEN + "\",\n"
                + "            \"status\": " + STATUS + ",\n"
                + "            \"statusDescricao\": \"" + STATUS_DESCRICAO + "\",\n"
                + "            \"urlCapturarDadosCartao\": \"" + URL_CAPTURAR_DADOS_CARTAO + "\",\n"
                + "            \"preferencial\": " + PREFERENCIAL + "\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 12,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"01/10/2019\",\n"
                + "            \"dataInsercao\": \"07/07/2017 01:14\",\n"
                + "            \"cartaoPan\": \"444433******1111\",\n"
                + "            \"cartaoValidade\": \"00/00\",\n"
                + "            \"bandeira\": \"\",\n"
                + "            \"cartaoToken\": \"872bd127-0daf-4875-b872-a4a57846180a1931\",\n"
                + "            \"gate2allToken\": \"213739b3-8f77-4c14-a8d7-323517997308\",\n"
                + "            \"status\": 2,\n"
                + "            \"statusDescricao\": \"Ativo\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/213739b3-8f77-4c14-a8d7-323517997308\",\n"
                + "            \"preferencial\": true\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 60,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"08/08/2017 18:05\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"dee54128-aa3c-4fe1-8bb0-587b494c875f\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/dee54128-aa3c-4fe1-8bb0-587b494c875f\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 349,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"fcc7df73-2d00-4c51-91e9-aab33634bd23\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/fcc7df73-2d00-4c51-91e9-aab33634bd23\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 350,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"7714f323-7b22-441c-aed6-87b646f00733\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/7714f323-7b22-441c-aed6-87b646f00733\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 351,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"c2fc9dd1-b995-4a12-846d-236d2917759b\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/c2fc9dd1-b995-4a12-846d-236d2917759b\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 352,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"026c3fca-e7ee-49c6-b6fe-a17ced815ccf\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/026c3fca-e7ee-49c6-b6fe-a17ced815ccf\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 353,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"cc18ba7f-aaaf-431a-bb93-036e90818ff6\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/cc18ba7f-aaaf-431a-bb93-036e90818ff6\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 355,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"940f4df9-82d8-4805-9efa-d359d5fecd00\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/940f4df9-82d8-4805-9efa-d359d5fecd00\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 357,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"6bffbe8d-9501-4e92-9df9-f2cb1350e16d\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/6bffbe8d-9501-4e92-9df9-f2cb1350e16d\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 395,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"bf9bbde8-a916-4f0d-b8af-59423b14afa9\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/bf9bbde8-a916-4f0d-b8af-59423b14afa9\",\n"
                + "            \"preferencial\": false\n"
                + "        }\n"
                + "    ],\n"
                + "    \"listaClienteCartao\": [\n"
                + "        {\n"
                + "            \"id\": 4,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"07/08/2017\",\n"
                + "            \"dataInsercao\": \"07/07/2017 01:14\",\n"
                + "            \"cartaoPan\": \"444433******1111\",\n"
                + "            \"cartaoValidade\": \"00/00\",\n"
                + "            \"bandeira\": \"\",\n"
                + "            \"cartaoToken\": \"0beb55b3-3c75-476d-b4ae-8071b0b2802c51\",\n"
                + "            \"gate2allToken\": \"49c18687-0cc7-485f-b16f-76d2d4dcf66e\",\n"
                + "            \"status\": 2,\n"
                + "            \"statusDescricao\": \"Ativo\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/49c18687-0cc7-485f-b16f-76d2d4dcf66e\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 12,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"01/10/2019\",\n"
                + "            \"dataInsercao\": \"07/07/2017 01:14\",\n"
                + "            \"cartaoPan\": \"444433******1111\",\n"
                + "            \"cartaoValidade\": \"00/00\",\n"
                + "            \"bandeira\": \"\",\n"
                + "            \"cartaoToken\": \"872bd127-0daf-4875-b872-a4a57846180a1931\",\n"
                + "            \"gate2allToken\": \"213739b3-8f77-4c14-a8d7-323517997308\",\n"
                + "            \"status\": 2,\n"
                + "            \"statusDescricao\": \"Ativo\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/213739b3-8f77-4c14-a8d7-323517997308\",\n"
                + "            \"preferencial\": true\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 60,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"08/08/2017 18:05\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"dee54128-aa3c-4fe1-8bb0-587b494c875f\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/dee54128-aa3c-4fe1-8bb0-587b494c875f\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 349,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"fcc7df73-2d00-4c51-91e9-aab33634bd23\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/fcc7df73-2d00-4c51-91e9-aab33634bd23\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 350,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"7714f323-7b22-441c-aed6-87b646f00733\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/7714f323-7b22-441c-aed6-87b646f00733\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 351,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"c2fc9dd1-b995-4a12-846d-236d2917759b\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/c2fc9dd1-b995-4a12-846d-236d2917759b\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 352,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"026c3fca-e7ee-49c6-b6fe-a17ced815ccf\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/026c3fca-e7ee-49c6-b6fe-a17ced815ccf\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 353,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"cc18ba7f-aaaf-431a-bb93-036e90818ff6\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/cc18ba7f-aaaf-431a-bb93-036e90818ff6\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 355,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"940f4df9-82d8-4805-9efa-d359d5fecd00\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/940f4df9-82d8-4805-9efa-d359d5fecd00\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 357,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"6bffbe8d-9501-4e92-9df9-f2cb1350e16d\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/6bffbe8d-9501-4e92-9df9-f2cb1350e16d\",\n"
                + "            \"preferencial\": false\n"
                + "        },\n"
                + "        {\n"
                + "            \"id\": 395,\n"
                + "            \"cliente\": {\n"
                + "                \"id\": 2,\n"
                + "                \"cpfCnpj\": \"085.106.388-88\",\n"
                + "                \"nomeRazaoSocial\": \"Marcio\",\n"
                + "                \"email\": \"marcio.martinelli@ntk.com.br\",\n"
                + "                \"telefone\": null\n"
                + "            },\n"
                + "            \"dataAtualizacao\": \"\",\n"
                + "            \"dataInsercao\": \"18/09/2017 22:48\",\n"
                + "            \"cartaoPan\": null,\n"
                + "            \"cartaoValidade\": null,\n"
                + "            \"bandeira\": null,\n"
                + "            \"cartaoToken\": null,\n"
                + "            \"gate2allToken\": \"bf9bbde8-a916-4f0d-b8af-59423b14afa9\",\n"
                + "            \"status\": 1,\n"
                + "            \"statusDescricao\": \"Token Pendente\",\n"
                + "            \"urlCapturarDadosCartao\": \"https://apidemo.gate2all.com.br/v1/save-card/bf9bbde8-a916-4f0d-b8af-59423b14afa9\",\n"
                + "            \"preferencial\": false\n"
                + "        }\n"
                + "    ]\n"
                + "}";

        DataToken d = WsHelper.unmarshal(toParse, DataToken.class);
        assertNotNull(d);
        List<ClienteCartao> cc = d.getData();
        testParseData(cc);
    }

    private void testParseData(List<ClienteCartao> cc) {
        assertNotNull(cc);
        assertEquals(ID, cc.get(0).getId());
        Cliente c = cc.get(0).getCliente();
        assertEquals(CLIENTE_ID, c.getId());
        assertEquals(CPF_CNPJ, c.getCpfCnpj());
        assertEquals(NOME_RAZAO_SOCIAL, c.getNomeRazaoSocial());
        assertEquals(EMAIL, c.getEmail());
        assertEquals(TELEFONE, c.getTelefone());
        assertEquals(DATA_INSERCAO, cc.get(0).getDataInsercao());
        assertEquals(CARTAO_PAN, cc.get(0).getCartaoPan());
        assertEquals(CARTAO_VALIDADE, cc.get(0).getCartaoValidade());
        assertEquals(BANDEIRA, cc.get(0).getBandeira());
        assertEquals(CARTAO_TOKEN, cc.get(0).getCartaoToken());
        assertEquals(GATE2ALLTOKEN, cc.get(0).getGate2allToken());
        assertEquals(STATUS, cc.get(0).getStatus());
        assertEquals(STATUS_DESCRICAO, cc.get(0).getStatusDescricao());
        assertEquals(URL_CAPTURAR_DADOS_CARTAO, cc.get(0).getUrlCapturarDadosCartao());
        assertEquals(PREFERENCIAL, cc.get(0).isPreferencial());

    }

}
